# Mergify configuration for qiskit-aer
queue_rules:
  - name: automerge
    merge_method: squash

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
      - or:
        - check-success=tests_linux (3.10, ubuntu-latest)
        - check-neutral=tests_linux (3.10, ubuntu-latest)
        - check-skipped=tests_linux (3.10, ubuntu-latest)
    actions:
      queue:
        name: automerge