name: Qiskit Neko Integration Tests
on:
  push:
  pull_request:
    branches: ['main', 'stable/*']
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  # Only cancel in PR mode.  In push mode, don't cancel so we don't see spurious test "failures".
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  neko:
    name: Qiskit Neko Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: Qiskit/qiskit-neko@main
        with:
          test_selection: backend
          repo_install_command: |
            pip install scipy==1.13.1
            pip install conan
            pip uninstall -y qiskit qiskit-terra qiskit-aer
            pip install -c constraints.txt .
