name: Qiskit Neko Integration Tests
on:
  push:
  pull_request:
    branches: ['main', 'stable/*']
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  neko:
    name: Qiskit Neko Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: Qiskit/qiskit-neko@main
        with:
          test_selection: backend
          repo_install_command: |
            pip install conan
            pip install .
