name: Qiskit Neko Integration Tests
on:
  push:
  pull_request:
    branches: ['main', 'stable/*']
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  neko:
    name: Qiskit Neko Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: Qiskit/qiskit-neko@main
        with:
          test_selection: backend
          repo_install_command: |
            mkdir ~/pip_tmp/
            pip install -v .
            rm -rf qiskit_aer
        env:
          TMPDIR: ~/pip_tmp/
